finn = User.create(user_name: 'Finn')
steve = User.create(user_name: 'Steve')
jane = User.create(user_name: 'Jane')
foo = User.create(user_name: 'Foo')
has = User.create(user_name: 'Has')
lyn = User.create(user_name: 'Lyn')
gin = User.create(user_name: 'Ginny')
harry = User.create(user_name: 'Harry')
ron = User.create(user_name: 'Ron')
hermione = User.create(user_name: 'Hermione')
siri = User.create(user_name: 'Siri')
mitch = User.create(user_name: 'Mitch')
sara = User.create(user_name: 'Sara')
kaitlin = User.create(user_name: 'Kaitlin')
rufus = User.create(user_name: 'Rufus')
vera = User.create(user_name: 'Vera')
hans = User.create(user_name: 'Hans')
gerrard = User.create(user_name: 'Gerrard')


yipp = Restaurant.create(rest_name: "Yipp's Lunch", rating: "4", address: "Over there")
danny = Restaurant.create(rest_name: "Danny's Pizza", rating: "4", address: "By Yipp's")
goon = Restaurant.create(rest_name: "Goon's Saloon", rating: "1", address: "New York st")
raf = Restaurant.create(rest_name: "Rafter's Drafters", rating: "3", address: "Imaginary")
